[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# 优化器设置
optimizer = true
optimizer_runs = 200

# Gas 报告
gas_reports = ["*"]

# 测试配置
verbosity = 3

# 格式化
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# RPC 端点（用于 Fork 测试）
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"